src/main/java/com/i_mmerce/disruptalookup/mvc/form/UserGroupForm.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.i_mmerce.disruptalookup.mvc.form;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import com.i_mmerce.disruptalookup.dao.PermissionComparator;
import com.i_mmerce.disruptalookup.dao.PermissionSorter;
import com.i_mmerce.disruptalookup.domain.Permission;
import com.i_mmerce.disruptalookup.domain.UserGroup;

/**
 *
 * @author Stuart Sontag
 */
public class UserGroupForm implements Serializable{
	public static long IMPORT_GP_ID_NOTSELECTED = -1;
	private Boolean locked;
    private UserGroup userGroup = new UserGroup();
    private boolean editMode = false;
    private Set<Permission> allPermissions = new HashSet<Permission>();;
    private Set<Permission> availPermissions = new HashSet<Permission>();
    private Set<Permission> selectedAvailPermissions = new HashSet<Permission>();;
    private Set<Permission> selectedPermissions = new HashSet<Permission>();;
    private Collection<UserGroup> importGroups = new HashSet<UserGroup>();
    private long selectedImportGroupId=IMPORT_GP_ID_NOTSELECTED;
    
    private static final PermissionComparator.Mode permCompMode = PermissionComparator.Mode.AreaAndDescripton;

    public UserGroupForm() {
        super();
    }

    private Permission getPermissionById(Long id){
    	for (Permission permission: allPermissions){
    		if (permission.getId().equals(id)){
    			return permission;
    		}
    	}
    	return null;
    }
    
    public void setSelectedAvailPermissionIds(Long[] ids){
    	selectedAvailPermissions = new HashSet<Permission>();
    	for (Long id :ids){
    		Permission permission = getPermissionById(id);
    		if (permission != null){
    			selectedAvailPermissions.add(permission);
    		}
    	}
    }

	public Long[] getSelectedAvailPermissionIds(){
		if (selectedAvailPermissions == null){
			return new Long[0];
		}
		Long[] ids = new Long[selectedAvailPermissions.size()];
		int i=0;
		for (Permission permission: selectedAvailPermissions){
			ids[i++]=permission.getId();
		}
		return ids;
    }    
    
    public void setSelectedPermissionIds(Long[] ids){
    	selectedPermissions = new HashSet<Permission>();
    	for (Long id :ids){
    		Permission permission = getPermissionById(id);
    		if (permission != null){
    			selectedPermissions.add(permission);
    		}
    	}
    }

	public Long[] getSelectedPermissionIds(){
		if (selectedPermissions == null){
			return new Long[0];
		}
		Long[] ids = new Long[selectedPermissions.size()];
		int i=0;
		for (Permission permission: selectedPermissions){
			ids[i++]=permission.getId();
		}
		return ids;
    }
	    
    
    public Set<Permission> getAllPermissions() {
		return allPermissions;
	}

	public void setAllPermissions(Set<Permission> allPermissions) {
		this.allPermissions = allPermissions;
	}


	public Set<Permission> getAvailPermissions() {
		return availPermissions;
	}

	public void setAvailPermissions(Set<Permission> availPermissions) {
		this.availPermissions = availPermissions;
	}
	
	public Collection<Permission> getSortedAvailPermissions() {
		return (new PermissionSorter(permCompMode)).sortCollection(availPermissions);
	}

	public void setSortedAvailPermissions(Collection<Permission> availPermissionsIn) {
		//this.availPermissions.clear();
		this.availPermissions = new HashSet<Permission>();
		this.availPermissions.addAll(availPermissionsIn);
	}	
	
	public void adjustUsedPermissions(){
		availPermissions = new HashSet<Permission>();
		availPermissions.addAll(allPermissions);
		if (userGroup.getPermissions() != null){
			availPermissions.removeAll(userGroup.getPermissions());
		}
	}
	
	public Set<Permission> getSelectedAvailPermissions() {
		return selectedAvailPermissions;
	}

	public void setSelectedAvailPermissions(Set<Permission> selectedAvailPermissions) {
		this.selectedAvailPermissions = selectedAvailPermissions;
	}

	public Set<Permission> getSelectedPermissions() {
		return selectedPermissions;
	}
	
	public Collection<Permission> getSortedCurrentPermissions(){
		return (new PermissionSorter(permCompMode)).sortCollection(userGroup.getPermissions());
	}

	public void setSelectedPermissions(Set<Permission> selectedPermissions) {
		this.selectedPermissions = selectedPermissions;
	}

	public UserGroup getUserGroup() {
		return userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
		setLocked(userGroup.getLocked());
	}

	public boolean isEditMode() {
		return editMode;
	}

	public void setEditMode(boolean editMode) {
		this.editMode = editMode;
	}

	public Boolean getLocked() {
		return locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Collection<UserGroup> getImportGroups() {
		return importGroups;
	}

	public void setImportGroups(Collection<UserGroup> importGroups) {
		this.importGroups = importGroups;
	}

	public long getSelectedImportGroupId() {
		return selectedImportGroupId;
	}

	public void setSelectedImportGroupId(long selectedImportGroupId) {
		this.selectedImportGroupId = selectedImportGroupId;
	}
	
	public void resetSelectedImportGroupId(){
		this.selectedImportGroupId = IMPORT_GP_ID_NOTSELECTED;
	}

    

}

src/main/java/com/i_mmerce/disruptalookup/mvc/BatchUploadUserController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.i_mmerce.disruptalookup.mvc;

import java.util.List;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

import com.i_mmerce.disruptalookup.domain.User;
import com.i_mmerce.disruptalookup.mvc.form.BatchUploadForm;
import com.i_mmerce.disruptalookup.service.BatchUserFactory;
import com.i_mmerce.disruptalookup.service.UserManager;

/** 
 *
 * @author Stuart Sontag
 */
@Controller
@RequestMapping("/admin/user")
@SessionAttributes({"allRoles","userForm","batchUploadedUsers"})
public class BatchUploadUserController{

    private static final Logger logger = Logger.getLogger(BatchUploadUserController.class);
    
    private static final String BASE_UPLOAD_DIRECTORY = "../statusview/upload/"; 
    private static final String CRM_ROLE_NAME = "ROLE_CRM";
    
    @Autowired
    private UserManager userManager;

    @RequestMapping(value="/batchupload.htm", method=RequestMethod.GET)
    public String getForm(Model model){
    	return "batchuploaduser";
    }
    
    @RequestMapping(value="/batchimport.htm", method=RequestMethod.POST)
    public String updateUser(@ModelAttribute("batchUploadForm") BatchUploadForm batchUploadForm,
    		Model model){
    	
    	BatchUserFactory batchUserFactory = new BatchUserFactory(/**userManager.getRole(CRM_ROLE_NAME),**/ userManager.getPasswordEncoder());
    	List<User> users = batchUserFactory.createUsersFromImportFile(BASE_UPLOAD_DIRECTORY, batchUploadForm);
    	for (User user: users){
    		logger.debug("About to persist: " + user.toSafeString());
    		userManager.persistUser(user, true);
    	}
    	model.addAttribute("batchUploadedUsers", users);
    	return "redirect:/admin/user/viewusers.htm";
    }  
    
    @RequestMapping(value="/batchdelete.htm", method=RequestMethod.GET)
    public String batchDelete(@ModelAttribute("batchUploadedUsers") List<User> batchUploadedUsers,
    		Model model){
    	for (User user: batchUploadedUsers){
    		logger.debug("About to delete: " + user.toSafeString());
    		userManager.deleteById(user.getId());
    	}
    	batchUploadedUsers.clear();
    	model.addAttribute("batchUploadedUsers", batchUploadedUsers);
    	return "redirect:/admin/user/viewusers.htm";
    }  
    
 
}

src/main/java/com/i_mmerce/disruptalookup/mvc/LogonController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.i_mmerce.disruptalookup.mvc;

import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
/**
 *
 * @author Stuart Sontag
 */
@Controller
public class LogonController {
    private static Logger logger = Logger.getLogger(LogonController.class);

  
    @RequestMapping(value = "/logon.htm", method = RequestMethod.GET)
    public String getIndexPage(ModelMap model){
    	logger.info("forwarding from /index.htm to 'pageIndex'");
    	return "logon";
    }

    @RequestMapping(value = "do/logon.htm", method = RequestMethod.GET)
    public String getIndexPageDo(ModelMap model){
    	logger.info("forwarding from do/logon.htm /index.htm to 'pageIndex'");
    	return "logon";
    }
	@RequestMapping(value="/logout.htm", method=RequestMethod.GET)
	public String getLogoutForm(final ModelMap model, HttpSession session) {
		return "logon";
	}
	
	@RequestMapping(value="/logout-success.htm", method=RequestMethod.GET)
	public String getLogoutSuccessForm(final ModelMap model, HttpSession session) {
		model.remove("currentUser");
		return "logon";
	}
	
	@RequestMapping(value="/logon-failure.htm", method=RequestMethod.GET)
	public String getLogonFailureForm(final ModelMap model, HttpSession session) {
		model.addAttribute("errorMsg", "Username/Password Authentication failure");
		return "logon";
	}
}

src/main/webapp/WEB-INF/jsp/baseLayout.jsp
<%-- 
    Document   : baseLayout.jsp
    Created on : 18/01/2010, 6:15:55 PM
    Author     : Stuart Sontag
--%>

<%@page contentType="text/html" pageEncoding="windows-1252"%>
<%@ page language="java"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title><tiles:getAsString name="title" /></title>
<s:url var="url_css" value="/css"/>
<s:url var="url_scripts" value="/scripts"/>
<link rel='stylesheet' type='text/css' href='${url_css}/style.css' />
<link rel='stylesheet' type='text/css' href='${url_css}/css-button.css' />
<link rel="stylesheet" type="text/css" href="${url_css}/start/jquery-ui-1.8.18.custom.css">
<link rel="stylesheet" type="text/css" href="${url_css}/superfish.css" media="screen">
<link rel="stylesheet" media="screen" href="${url_css}/superfish-vertical.css" />
<link rel="stylesheet" media="screen" href="${url_css}/defaultTheme.css" />
<script type="text/javascript" src="${url_scripts}/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="${url_scripts}/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="${url_scripts}/hoverIntent.js"></script>
<script type="text/javascript" src="${url_scripts}/superfish.js"></script>
<script type="text/javascript" src="${url_scripts}/jquery.jstree.js" ></script>
<link href="${url_css}/jquery.treeview.css" rel="stylesheet">
<!--script type="text/javascript" src="/statusview/scripts/jquery.treeview.js"-->
<script type="text/javascript">
	$(function(){
		jQuery('ul.sf-menu').superfish();
	});
</script>

</head>
<body>

<div id="header-wrap">
	<div id="header-area"><tiles:insertAttribute name="header" /></div>
</div>
<div id="content-area">
	<!--div id="leftnav"><tiles:insertAttribute name="navigation" /></div-->
	<div id="main-area"><tiles:insertAttribute name="body" /></div>
	<div id="footer-area"><tiles:insertAttribute name="footer" /></div>
</div> <%-- content-area --%>

</body>

</html>

src/main/webapp/WEB-INF/jsp/batchuploaduser.jsp
<%-- 
    Document   : logon
    Created on : 25/01/2010, 6:22:33 PM
    Author     : Stuart Sontag
--%>
<%@ page contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<script type="text/javascript" src="/statusview/scripts/jquery.busy.min.js"></script>
	<sec:authorize access="hasAnyRole('ROLE_ADMINISTRATOR')">
		<spring:url var="actionUrl" value="/admin/user/batchimport.htm" />
		<spring:url var="batchDeleteUrl" value="/admin/user/batchdelete.htm" />
	</sec:authorize>
	<spring:url var="busyImgUrl" value="/images/busy.gif" />
	<sec:authorize access="hasAnyRole('ROLE_ADMINISTRATOR')">
    <form:form method="POST" action="${actionUrl}" modelAttribute="batchUploadForm">
               <label for="filename">Upload file name located in $TOMCAT_HOME/statusview/upload directory</label>
               <input id="filename" type="text" name="filename" />
               <p>
          	   <label for="columnSeparator">Column Seperator</label>
          	   <input id="columnSeparator" name="columnSeparator" type="text" value=";"/>
          	   </p>          
          	 <fieldset><legend>Type of Row Data</legend>
          	   <label for="typeCol">Type Column Number (Starting from 1)</label>
          	   <input id="typeCol" name="typeCol" type="number" value="1"/>
          	   <label for="typeRegex">Type Column Selected Value Regex</label>
          	   <input id="typeRegex" name="typeRegex" type="text" value="CUSTOMER" />
            </fieldset>
            <fieldset><legend>Boris Code</legend>
			   <label for="borisCol">boris code Column Number (Starting from 1)</label>
          	   <input id="borisCol" name="borisCol" type="number" value="2"/>            
            	<label for="borisFilterModeStr">Boris filtering</label>
            	<select id="borisFilterModeStr" name="borisFilterModeStr" >
            		<option value="Unchanged" >unchanged</option>
            		<option value="ToLowercase">To Lowercase</option>
            		<option value="ToUppercase" selected="selected">To Uppercase</option>
            	</select>
            </fieldset>
          	<fieldset><legend>Username</legend>
 				<label for="usernameCol">Username Column Number (Starting from 1)</label>
          	   <input id="usernameCol" name="usernameCol" type="number" value="2"/>
               <p>
          	   <label for="usernamePrefix">Username Prefix</label>
          	   <input id="usernamePrefix" name="usernamePrefix" type="text" value=""/>          	   
         	   <label for="usernameFilterModeStr">Username filtering</label>
               <select id="usernameFilterModeStr" name="usernameFilterModeStr" >
            		<option value="Unchanged" >unchanged</option>
            		<option value="ToLowercase" selected="selected">To Lowercase</option>
            		<option value="ToUppercase">To Uppercase</option>
               </select>
          	   <label for="usernameSuffix">Username Suffix</label>
          	   <input id="usernameSuffix" name="usernameSuffix" type="text" value="VPNreport"/>
          	   </p>          
            </fieldset>
            <fieldset><legend>Password</legend>
          	   <label for="passwordCol">Password Column Number (Starting from 1. Setting to 0 assigns all passwords to constant = prefix + suffix)</label>
          	   <input id="passwordCol" name="passwordCol" type="number" value="2"/>
        	   
           	   <p>
          	   <label for="passwordPrefix">password prefix</label>
          	   <input id="passwordPrefix" name="passwordPrefix" type="text" value=""/>
          	   <label for="passwordFilterModeStr">Password filtering</label>
               <select id="passwordFilterModeStr" name="passwordFilterModeStr" >
            		<option value="Unchanged" >unchanged</option>
            		<option value="ToLowercase" selected="selected">To Lowercase</option>
            		<option value="ToUppercase">To Uppercase</option>
               </select>          	   
          	   <label for="passwordSuffix">password suffix</label>
          	   <input id="passwordSuffix" name="passwordSuffix" type="text" value="VPNreport"/>
          	   </p>             	   
          	</fieldset>
          
          	<c:if test="${errorMsg != null}">
				<div class="errormsg"> ${errorMsg}</div>
			</c:if>
            <p><input id="uploadBtn" type="submit" value="Upload" />
             <c:if test="${not empty batchUploadedUsers}" >
             	<input id="deleteAllUploadedBtn" type="button" value="Delete Batch Uploaded Users" />
             </c:if>
            </p>
    </form:form>
    
    <script type="text/javascript">
   // $(function(){
   // 	jQuery().busy("preload", {img : "${busyImgUrl}" });
   // })
    $("#uploadBtn").click(function(){
    	$(this).busy({img : "${busyImgUrl}" });
    	return true;
    })
    <c:if test="${not empty batchUploadedUsers}" >
	     $("#deleteAllUploadedBtn").click(function(){
	      	//var ans = confirm("Are you sure that you want delete User: " + uname);
	      	//return (ans);
	      	$('<div>').dialog({
	      		open: function(){$(this).text("Are you sure that you want delete the entire batch of recently uploaded Users?");},
	      		modal: true,
	      		title: 'Confirm delete All Batch Uploaded Users',
	      		buttons: {
	      			Yes: function(){ 
	      				$("#deleteAllUploadedBtn").busy({img : "${busyImgUrl}" });
	      				   open("${batchDeleteUrl}");
	      					$(this).dialog('close');
	      				 },
	      			No:  function(){
	      					$(this).dialog('close');	        				
	      				}
	      		}
	      	})
	      	return false;
	       });
     </c:if>
    </script>
    </sec:authorize>
    

src/main/webapp/WEB-INF/jsp/createupdateusergroup.jsp
<%-- 
    Document   : logon
    Created on : 25/01/2010, 6:22:33 PM
    Author     : Stuart Sontag
--%>
<%@ page contentType="text/html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

	<sec:authorize access="hasAnyRole('ROLE_CRM')">
		<spring:url var="updateUserGroupUrl" value="/group/update.htm" />
	</sec:authorize>
	<sec:authorize access="hasAnyRole('PERM_GROUP_ADMIN')">
		<spring:url var="createUserGroupUrl" value="/admin/group/create.htm" />
		<spring:url var="updateUserGroupUrl" value="/admin/group/update.htm" />
		<spring:url var="importPermissionsUrl" value="/admin/group/importpermissions.htm" />
		<spring:url var="getUserGpPermissionsUrl" value="/admin/group/getperms" />
		<spring:url var="addSelectedAvailPermissionUrl" value="/admin/group/addselectedavailpermissions.htm" />
		<spring:url var="deleteSelectedPermissionsUrl" value="/admin/group/deleteselectedpermissions.htm" />
		<spring:url var="backToUrl" value="/admin/group/viewusergroups.htm"/>
	</sec:authorize>
    <form:form method="POST" modelAttribute="userGroupForm">
      <table class="forminputtbl" >
       	  <tr>
       	  		<td>Locked:</td><td><form:checkbox id="lockedElem" path="locked" value="locked"/></td>
       	  </tr>      
          <tr>
              <td>Group Name:</td><td><form:input path="userGroup.name" size="80" /></td>
          </tr>
          <tr>
              <td>Description:</td><td><form:input path="userGroup.description" size="80" /></td>
          </tr>
          <tr>
              <td>Network:</td><td><form:input path="userGroup.network.name" size="80" disabled='true' /></td>
          </tr>
          <sec:authorize access="hasAnyRole('PERM_GROUP_ADMIN')">
          <tr><td  colspan="2">
          <legend>User Group Permissions</legend>
          <table class="forminnerinputtbl" >
		   <tr>
          	   <td style="width: 300px;"><label for="importGroupsSelect">Groups to import: </label>
          	   <select id="importGroupsSelect" size="15" style="width: 100%;" name="selectedImportGroupId" value="${userGroupForm.selectedImportGroupId}"/>
          	   			<option value="-1">-- Select Group to Import its Permissions --</option>
		         	 	<c:forEach items="${userGroupForm.importGroups}" var="group">
								<option value="${group.id}">${group.name} 
								 <c:if test="${group.locked == true}">: LOCKED</c:if>
								</option>
					 	</c:forEach>
			 	</select>          	   
          	   </td>
          	   <td></td>
          	    <td style="width: 300px;"><div id="userGroupPermsDiv" style="width: 280px;"/></td>
          </tr>
          <tr style="height: 30px;"><td colspan="2" style="height: 30px;"></td>
          	<td style="height: 30px;"><input id="importPermissionsButton" type="button" value="Import &darr;" class="innerFormButton button blue" /></td>
          </tr>
          </table> 
          </td></tr>         
           <tr><td  colspan="2">
           <!-- c:if test="${userGroupForm.userGroup.id != null}"-->
		  <fieldset>
		   <table class="forminnerinputtbl" >	
		   <tr>
          	   <td style="width: 300px;"><label for="availPermissions">Available Permissions: </label>
          	   <form:select id="availPermissions" size="15" style="width: 100%;" path="selectedAvailPermissionIds" multiple="true" items="${userGroupForm.sortedAvailPermissions}" itemLabel="description" itemValue="id" /></td>
          	   
          	   <td><input id="addPermissionsButton" type="button" value="Add &rarr;" class="innerFormButton button blue" /></br></br>
				<input id="deletePermissionsButton" type="button" value="&larr; Remove" class="innerFormButton button blue" /></td>
          	   
          	   <td style="width: 300px;"><label for="currentPermissions">Current Permissions: </label>
          	   <form:select id="currentPermissions" size="15"  style="width: 100%;" path="selectedPermissionIds" multiple="true" items="${userGroupForm.sortedCurrentPermissions}" itemLabel="description" itemValue="id" /></td>
          	   
          </tr>          
		 </table>
		 </fieldset>
		 <!--/c:if-->
		 </td></tr>
		 </sec:authorize>         
          <tr>
              <td colspan="2">
              	<c:if test="${userGroupForm.editMode == false}">
                  <input id="createUpdateUserGroupButton" type="button" value="Create User Group" class="button blue" />
                 </c:if>
              	<c:if test="${userGroupForm.editMode == true}">
                  <input id="createUpdateUserGroupButton" type="button" value="Save User Group" class="button blue" />
                 </c:if>
                 <input id="backButton" type="button" value="Back" class="button blue" style="position: relative; left: 500px;" />  
              </td>
          </tr>
          <tr><td colspan="2">
          	<c:if test="${errorMsg != null}">
				<div class="errormsg"> ${errorMsg}</div>
			</c:if>
          </td></tr>
      </table>
    </form:form>
    
    
    <script type="text/javascript">	
		$('#addPermissionsButton').click(function() {
			$('#userGroupForm').attr("action","${addSelectedAvailPermissionUrl}?scrolltop="+$(window).scrollTop());
			$('#userGroupForm').submit();
		});
		
		
		$('#importPermissionsButton').click(function() {
			if($('#importGroupsSelect').val()>-1){
				$('#userGroupForm').attr("action","${importPermissionsUrl}?scrolltop="+$(window).scrollTop());
				$('#userGroupForm').submit();
			}
		});
		
		function updateUserGroupsPerms(){
			var queryS = "${getUserGpPermissionsUrl}?gpid=" + $('#importGroupsSelect').val();
			$('#userGroupPermsDiv').load(queryS);
		}
		
		$('#importGroupsSelect').change(function(){
			updateUserGroupsPerms();
		});		
    
		$('#deletePermissionsButton').click(function() {
			$('#userGroupForm').attr("action","${deleteSelectedPermissionsUrl}?scrolltop="+$(window).scrollTop());
			$('#userGroupForm').submit();
		});
		
		$('#createUpdateUserGroupButton').click(function() {
          	<c:if test="${userGroupForm.editMode == false}">
				$('#userGroupForm').attr("action","${createUserGroupUrl}");
			</c:if>
			<c:if test="${userGroupForm.editMode == true}">
				$('#userGroupForm').attr("action","${updateUserGroupUrl}");
			</c:if>
			//enable form before submission
			enableDisableFormElements(true);
			$('#userGroupForm').submit();
		});
		
		$('#backButton').click(function() {
			open("${backToUrl}");
		});	
		
		function enableDisableFormElements(enable){
			if (enable){
				$("input").removeAttr("disabled");
				$("select").removeAttr("disabled");			
			} else {
				$("input").attr("disabled","disabled");
				$("select").attr("disabled","disabled");				
			}
			//Set locked Checkbox depending on permission no enable parameter
			<sec:authorize access="hasAnyRole('PERM_GROUP_LOCKED_ADMIN')">
				$("#lockedElem").removeAttr("disabled");
				$("#createUpdateUserGroupButton").removeAttr("disabled");
			</sec:authorize>
			<sec:authorize access="!hasAnyRole('PERM_GROUP_LOCKED_ADMIN')">
				$("#lockedElem").attr("disabled","disabled");
			</sec:authorize>
			$("#backButton").removeAttr("disabled");
		}
		
		$("#lockedElem").change(function(){
			enableDisableFormElements(!this.checked);
		})
		$(function(){
			<c:if test="${userGroupForm.locked == true}" >
				enableDisableFormElements(false);
			</c:if>
			<c:if test="${userGroupForm.locked == false}" >
				enableDisableFormElements(true);
			</c:if>	
			
			$('#importGroupsSelect').val("${userGroupForm.selectedImportGroupId}");
			updateUserGroupsPerms();
			
			<c:if test="${!empty scrollTop}">
				$(window).scrollTop(${scrollTop})
			</c:if>
		});
    </script>

src/main/webapp/WEB-INF/jsp/footer.jsp
<%-- 
    Document   : footer
    Created on : 22/01/2010, 6:06:42 PM
    Author     : Stuart Sontag
--%>

<%@page contentType="text/html" %>

<div style="padding-top: 50px; clear: both;">
<hr/>
<span>Copyright &copy; <%= new java.util.Date().getYear() + 1900 %> I-mmerce Pty Ltd</span>
</div>
<div id='console' />